import type { Theme } from "./types";

// YaVendio design system. Status buckets keep the green=up / red=down
// convention on the earthy palette: success→forest, warning→caramel,
// destructive→red-clay, info→teal. Values ported from the yavcn-ui registry.
export const YAVENDIO_THEME = {
  id: "yavendio" as const,
  name: "YaVendio",
  author: { name: "@yavendio", url: "https://yavendio.com" },
  light: {
    "--radius": "0.75rem",
    "--background": "#fafaf9",
    "--foreground": "#1c1917",
    "--card": "#ffffff",
    "--card-foreground": "#1c1917",
    "--popover": "#ffffff",
    "--popover-foreground": "#1c1917",
    "--border": "#e7e5e4",
    "--input": "#e7e5e4",
    "--primary": "#96408f",
    "--primary-foreground": "#ffffff",
    "--secondary": "#f5f5f4",
    "--secondary-foreground": "#292524",
    "--muted": "#f5f5f4",
    "--muted-foreground": "#78716c",
    "--accent": "#f5f5f4",
    "--accent-foreground": "#292524",
    "--ring": "#96408f",
    "--success": "#12a457",
    "--warning": "#efa50a",
    "--destructive": "#e0443b",
    "--info": "#1596ad",
  },
  dark: {
    "--radius": "0.75rem",
    "--background": "#0c0a09",
    "--foreground": "#fafaf9",
    "--card": "#1c1917",
    "--card-foreground": "#fafaf9",
    "--popover": "#1c1917",
    "--popover-foreground": "#fafaf9",
    "--border": "#44403c",
    "--input": "#44403c",
    "--primary": "#dca6e6",
    "--primary-foreground": "#1c1917",
    "--secondary": "#292524",
    "--secondary-foreground": "#fafaf9",
    "--muted": "#292524",
    "--muted-foreground": "#a8a29e",
    "--accent": "#292524",
    "--accent-foreground": "#fafaf9",
    "--ring": "#dca6e6",
    "--success": "#38cc80",
    "--warning": "#f7c33f",
    "--destructive": "#f4746c",
    "--info": "#4fbdd6",
  },
} as const satisfies Theme;
